### ISSUE TITLE
Nedlasting av besvarelser

### ISSUE THREAD

**Issue by jon-mey** [simennj/itsdownloading#4]
Konge det her. Men mulig å få til inkludering av leverte besvarelser?

**Comment by simennj** [comment]
Burde være mulig å få til ved å legge til besvarelser i download_urls her.
```python
def download_from_essay_page(directory, link_url):
    essay_page = session.get(link_url)
    download_urls = fromstring(essay_page.content).xpath(
        '//div[@id="EssayDetailedInformation_FileListWrapper_FileList"]/ul/li/a/@href')
    for download_url in download_urls:
        download_file(directory, download_url)
```
Skal se nærmere på det neste uke når eksamensperioden er over.

**Comment by bartvbl** [comment]
@jameyer If I can plug my version; it catches as good as everything, including submitted answers and grades:

https://github.com/bartvbl/itslearning-dumper

**Comment by simennj** [comment]
Added support for downloading assignment answers in v1.2.0 today.
