### ISSUE TITLE
Nedlasting av forum

### ISSUE THREAD

**Issue by EAR95** [simennj/itsdownloading#8]
Hei! :)

Er det mulig å gjøre det slik at også forum inne på itslearning lastes ned?

**Comment by simennj** [comment]
Tror dessverre ikke jeg jeg rekker å legge det til før 15. juli. Har ikke lenger så mye tid til overs til å videreutvikle scriptet pga. sommerjobb, men hvis noen andre sender en pull request så kan jeg merge den.

Du kan evt. prøve https://github.com/bartvbl/itslearning-dumper. Har ikke testet den selv men den skal visstnok ta med forum også.

**Comment by bartvbl** [comment]
Can confirm.

Min versjon tar med forum også.

**Comment by mumitrollet** [comment]
Jeg klarer å skrive inn brukernavnet, men det skjer ingenting når jeg prøver å skrive inn passordet. hjelp?

**Comment by simennj** [comment]
@mumitrollet Er du sikker på at det ikke skjer noe? Har fått en del mail om det samme der det har vist seg at de hadde blitt forvirret av at det ikke vises noe når man skriver inn passordet. Har du prøvd å trykke enter? Forresten fint om du opprettet en ny issue istedenfor hvis du fortsatt har problemer, denne issuen gjelder i utgangspunktet kun en forespørsel om nedlastning fra forum.

@bartvbl Fint, da markerer jeg denne som wontfix og stenger den ned. Kan eventuelt åpne den igjen senere om nødvendig.
