### ISSUE TITLE
Passord

### ISSUE THREAD

**Issue by simennyu** [simennj/itsdownloading#9]
Etter å ha skrevet inn brukernavnet kommer feltet hvor jeg skal skrive passord, her er det ikke mulig å skrive inn noe, hverken tall eller bokstaver, eneste tasten som gjør noe er "enter" som tar meg tilbake til å skrive inn brukernavnet.

**Comment by simennj** [comment]
Passordfunksjonen i Python viser ikke noen tegn når man taster inn passordet. Er du sikker på at du både har valgt riktig studiested og at du skrev inn riktig passord før du trykket enter?

Isåfall, hvilket operativsystem kjører du og hvilket program (terminal/cmd) kjøres scriptet i? Hvis du kjører det gjennom Python direkte så kan du prøve [gui branchen](https://github.com/simennj/itsdownloading/tree/gui) (kjør qt.py) og se om det fungerer der.

**Comment by simennyu** [comment]
Aner ikke hva som gikk galt første gangen, men kjørte gjennom Python nå og fungerte fint. 
Prøvde å reprodusere i cmd nå og det fungerer der også, så beklager bryet. Antagelig lå problemet bare hos meg og passord innskrivingen min ;)
